Some QOL improvements
ebarnard/rust-plist pull request #117
Opened 2023-04-04 01:00 UTC by naturecodevoid

Hi, this PR has a few QOL improvements. If you want me to remove anything, please tell me!
- Update dependencies and use serde's `derive` feature instead of the `serde_derive` crate
- Remove extern crates since I think best practice is to `use` them
- Improve dictionary `insert` function to take `impl Into<String>` and `impl Into<Value>`. This shouldn't break any previous usage, but it would allow for this:
```rs
// Old usage
let mut dictionary = Dictionary::new();
dictionary.insert("string".to_string(), "test".into());
dictionary.insert("integer".to_string(), 1.into());

// New usage (way easier!)
let mut dictionary = Dictionary::new();
dictionary.insert("string", "test");
dictionary.insert("integer", 1);
```
If there's any other functions that would benefit from `impl Into`, I think it would be good to add it to those but `insert` was the main one I saw.
- Implement `From<Vec<u8>>` for `Value`

All tests are passing.

2023-04-13 14:34 UTC, naturecodevoid commented
Hey @ebarnard, sorry to bother you, do you have any thoughts on these changes? would it be possible to use `impl Into` for arguments, or should I make a fork with those changes since they don't seem to be backwards compatible?

2023-04-17 17:32 UTC, ebarnard requested changes
Hi. Thanks for the PR. Unfortunately I don't think it's possible to use `Into<Value>` without it being a breaking change. 

Maybe it could be done with [default type parameters](https://rust-lang.github.io/rfcs/0213-defaulted-type-params.html) e.g.
```rust
pub fn insert<V:Into<Value>=Value>(&mut self, k: String, v: impl Into<Value>) -> Option<Value> {
    ...
}
```
when that becomes stable.

2023-04-17 17:32 UTC, ebarnard commented on Cargo.toml
> +time = { version = "0.3.20", features = ["parsing", "formatting"] }
I tend to not bump versions. Cargo will use the latest semver compatible version by default, and this way the version number defines the minimum supported version which I prefer.

2023-04-17 17:32 UTC, ebarnard commented on src/dictionary.rs
> +    pub fn insert(&mut self, k: impl Into<String>, v: impl Into<Value>) -> Option<Value> {
This isn't backwards compatible I'm afraid. It would be nice to have `Into<Value>` but I don't it warrants a major version bump.

2023-04-17 17:32 UTC, ebarnard commented on src/value.rs
> +impl From<Vec<u8>> for Value {
Can you use `From<Data>` here? `From<Vec<u8>>` could make sense for both array or data and I'd rather avoid the ambiguity.

2023-04-17 22:50 UTC, naturecodevoid commented
I can revert the breaking changes and dependency update. May I have your permission to make a plist2 crate which would be a fork of this one with those breaking changes (unless you're willing to increase the major version to 2)?

2023-04-18 20:46 UTC, ebarnard commented
I'm not sure there's any benefit to releasing either a major version or new crate for a very minor ergonomoic change, and a reasonable number of downsides to doing either. With that said, you don't need permission to fork open source software if you feel that it is worth doing.

2023-04-18 22:54 UTC, naturecodevoid commented
Would you be willing to add this change as an optional feature?

2023-04-21 14:05 UTC, ebarnard commented
What is your use case for this change? Do you have a lot of hand-written code where you are having to write `.into()`?

2023-04-21 15:41 UTC, naturecodevoid commented
https://github.com/SideStore/minimuxer/blob/master/src/muxer.rs#L178

yes, and I expect we will have to do a lot more of this if/when we reimplement some C libraries we depend on in Rust.

2023-04-22 10:36 UTC, ebarnard commented
If it's just for one project, would it not be simpler to define your own extension trait. e.g. 

```rust
pub trait DictionaryExt {
    fn add(&mut self, k: impl Into<String>, v: impl Into<Value>) -> Option<Value>;
}

impl DictionaryExt for Dictionary { ... }
```

2023-04-22 19:01 UTC, naturecodevoid commented
It would be for multiple projects, and I'd rather not copy that trait to every project.

I've reverted the dependency update, breaking change and now the From implementation uses Data instead of Vec<u8>. Let me know if there's anything else you want me to change.

2023-04-29 15:08 UTC, naturecodevoid commented
Removing `extern crate` may drop support for older compilers

2023-06-10 22:10 UTC, closed without merging

2023-06-10 22:12 UTC, naturecodevoid commented
I might separate this PR into smaller ones in the future, but other than implementing From<Data> for Value it's pretty useless

DictionaryExt trait might be useful in the future, with things like From<[(K, V)]> and append(). It would also be good to make a ToBytes trait or something similar as a helper method and `from_value` similar to serde_json.