add a plist macro - copied from serde_json
ebarnard/rust-plist pull request #143
Opened 2024-06-25 19:36 UTC by aluedeke

i copied the json macro from serde and modified it i create plist::Value from json annotation. This is super handy when working with lockdown and usbmuxd messages.

I am relatively new to rust, thus i would appreciate any feedback.

The original macro was copied from here:
https://github.com/serde-rs/json/blob/c4f24f3be29a3d096d3ac7b1d5594777a613ec0d/src/macros.rs

2024-06-27 07:48 UTC, ebarnard requested changes
Thanks for this, it looks really useful. Please could you add some tests for the macro (hopefully can be copied from `serde_json` as well.

2024-06-27 07:48 UTC, ebarnard commented on src/lib.rs
> +#[cfg(feature = "serde")]
This doesn't look like it uses any serde features, so I don't think needs the `cfg`.

2024-07-01 10:57 UTC, aluedeke commented
@ebarnard added tests as well 
- removed support for null
- fixed support for boolean

2024-07-03 18:28 UTC, aluedeke commented on src/macros.rs
> +        $crate::to_value(&$other).unwrap()
this actually requires the serde feature @ebarnard should be put the whole macro behind that the serde feature?

2025-08-20 12:34 UTC, aluedeke commented
@ebarnard anything else i can do to make it easier to merge  this?

2025-09-15 17:14 UTC, ebarnard requested changes
Hi. Sorry this took me so long to get round to looking at. I think it looks good to go barring a few nits.

2025-09-15 17:14 UTC, ebarnard commented on src/macros.rs
> +        $crate::to_value(&$other).unwrap()
I'd be tempted to initially limit this to things that implement `Into<Value>`. If someone wants to serialise something they can always call `to_value` on it themselves.

2025-09-15 17:14 UTC, ebarnard commented on src/macros.rs
> +/// Variables or expressions can be interpolated into the PList literal. Any type
Maybe "Variables or expressions can be interpolated into the literal"? There are no nice casings of "plist".

2025-09-15 17:14 UTC, ebarnard commented on src/macros.rs
> +/// Construct a `plist::Value` from a JSON literal.
How about "Construct a `plist::Value` from a JSON-like literal."? As some things will serialise differently to JSON.

2025-11-19 03:37 UTC, oslo254804746 commented
When will these changes be released? Currently, I'm implementing this using my own code; if the `plist` library supports it, it will significantly reduce the amount of code required.
```rust
#[doc(hidden)]
#[macro_export]
macro_rules! __plist_value_impl {
    // 布尔值
    (true) => {
        ::plist::Value::Boolean(true)
    };
    (false) => {
        ::plist::Value::Boolean(false)
    };

    // 嵌套字典 { ... }
    ({ $($key:expr => $value:expr),+ $(,)? }) => {
        ::plist::Value::Dictionary($crate::plist_dict! { $($key => $value),+ })
    };

    // 数组 [...]
    ([ $($item:expr),* $(,)? ]) => {
        ::plist::Value::Array(vec![
            $($crate::plist_value!($item)),*
        ])
    };

    // 默认情况 - 使用 Into trait
    ($value:expr) => {{
        use $crate::IntoPlistValue;
        let v = $value;
        v.into_plist_value()
    }};
}




/// 将 Rust 值转换为 plist::Value 的宏
#[macro_export]
macro_rules! plist_value {
    // 字符串字面量
    ($value:expr) => {{
        $crate::__plist_value_impl!($value)
    }};
}
#[macro_export]
macro_rules! plist_dict {
    // 空字典
    {} => {
        ::plist::Dictionary::new()
    };

    // 递归处理键值对
    { $($key:expr => $value:tt),+ $(,)? } => {{
        let mut dict = ::plist::Dictionary::new();
        $(
            dict.insert($key.to_string(), $crate::__plist_value_impl!($value));
        )+
        dict
    }};
}





/// 辅助函数 - 将 Rust 类型转换为 plist::Value
#[doc(hidden)]
pub fn __convert_to_plist_value<T>(value: T) -> plist::Value
where
    T: IntoPlistValue,
{
    value.into_plist_value()
}
```

2026-04-27 08:01 UTC, closed without merging